// Сквозная проверка основных сценариев: node scripts/e2e-smoke.mjs [baseUrl] [outDir]
import { chromium } from "playwright";
const base = process.argv[2] ?? "http://localhost:3000";
const out = process.argv[3] ?? "/tmp";
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push("PAGEERROR " + e.message));
page.on("console", (m) => m.type() === "error" && errors.push("CONSOLE " + m.text()));
const shot = (name) => page.screenshot({ path: `${out}/${name}.png`, fullPage: true });
const email = `user${Date.now()}@test.local`;

await page.goto(`${base}/register?theme=love`);
await page.fill("#name", "Алия");
await page.fill("#email", email);
await page.fill("#password", "secret123");
await page.check("input[name=consent]");
await page.click("button[type=submit]");
await page.waitForURL(/\/books\/new/);
await page.fill("#recipientName", "Марғұлан");
await page.getByRole("button", { name: "Женщина" }).click();
await shot("01-new-book");
await page.click("button[type=submit]");
await page.waitForURL(/\/books\/[0-9a-f-]{36}$/);
const bookUrl = page.url();
await shot("02-hub");
await page.goto(`${bookUrl}/questions?q=2`);
await page.fill("#answer", "Мы встретились в самый обычный вторник, когда в Алматы шёл первый снег.\nЯ опаздывала на встречу, а ты держал дверь кофейни.");
await page.waitForTimeout(1800);
await shot("03-questions");
await page.getByRole("button", { name: /Далее/ }).click();
await page.fill("#answer", "Ты показался мне очень серьёзным — пока не улыбнулся.");
await page.getByRole("button", { name: /Все вопросы/ }).click();
await page.waitForTimeout(500);
await shot("04-drawer");
await page.keyboard.press("Escape");
await page.waitForTimeout(1500);
await page.reload();
const val = await page.inputValue("#answer");
console.log("persisted answer:", JSON.stringify(val));
await page.goto(`${bookUrl}/cover`);
await page.waitForTimeout(500);
await shot("05-cover");
console.log("book", bookUrl);
console.log(errors.length ? errors.join("\n") : "no browser errors");
await browser.close();
