/**
 * Коллекция обложек на настоящих снимках (Unsplash, бесплатная лицензия Unsplash License:
 * коммерческое использование разрешено, указание автора не обязательно). Файлы — assets/cover-photos/<id>.jpg,
 * авторы — в поле credit. Раскладка и отрисовка — src/lib/book/photo-cover.ts.
 */
import type { CoverTemplate, CoverTextStyle } from "./covers";
import { photoTemplate, type PhotoLayout, type PhotoTemplateData } from "./photo-cover";
import type { FontKey } from "./fonts";

type Def = Omit<PhotoTemplateData, "name" | "subtitle" | "names" | "spine" | "back" | "layout"> & {
  layout: Omit<PhotoLayout, "photo"> & { size: [number, number]; credit: string };
  /** Цвет имён и подзаголовка. */
  soft: string;
  subtitle?: Partial<CoverTextStyle>;
  names?: Partial<CoverTextStyle>;
  /** Шрифт оборота и корешка — по умолчанию как у названия. */
  font?: FontKey;
  back?: Partial<PhotoTemplateData["back"]>;
};

const serifItalic = (color: string, size = 0.1): CoverTextStyle => ({ font: "cormorant", size, color, weight: 500, italic: true, lineHeight: 1.05 });
const capsNames = (color: string): CoverTextStyle => ({ font: "montserrat", size: 0.024, color, weight: 500, upper: true, tracking: 0.28 });

function def(d: Def): CoverTemplate {
  const { size, credit, ...layout } = d.layout;
  const font = d.font ?? d.title.font;
  return photoTemplate({
    id: d.id,
    // Названия встроенных обложек — в словарях i18n (catalog.covers).
    name: { ru: d.id, kk: d.id },
    mood: d.mood,
    layout: { ...layout, photo: { key: d.id, width: size[0], height: size[1], credit } },
    textArea: d.textArea,
    justify: d.justify,
    title: d.title,
    subtitle: { font, size: 0.045, color: d.soft, italic: true, ...d.subtitle },
    names: { ...capsNames(d.soft), ...d.names },
    ornament: d.ornament,
    spine: { color: d.title.color, font },
    back: { color: d.title.color, font, ...d.back },
  });
}

/** Текст сверху, над снимком. */
const TOP = { x: 0.1, y: 0.08, w: 0.8, h: 0.28 };
/** Текст снизу. */
const BOTTOM = { x: 0.1, y: 0.65, w: 0.8, h: 0.27 };
/** Область текста на обороте — та же, что на лице. */
const backTop = { area: { x: 0.14, y: 0.1, w: 0.72, h: 0.3 } };
const backBottom = { area: { x: 0.14, y: 0.6, w: 0.72, h: 0.3 } };
const backMiddle = { area: { x: 0.14, y: 0.3, w: 0.72, h: 0.4 } };

export const photoCollection: CoverTemplate[] = [
  // ─── романтика ───
  def({
    id: "peony",
    mood: "romance",
    layout: { size: [4800, 3600], credit: "Haberdoedas / Unsplash", focus: { x: 0.5, y: 0.29 }, zoom: 0.82, base: "#000000", back: "photo" },
    textArea: { x: 0.1, y: 0.07, w: 0.8, h: 0.26 },
    justify: "center",
    title: serifItalic("#F2E6D0"),
    soft: "#CDBEA4",
    names: { color: "#BFA57A" },
    ornament: { kind: "line", color: "#8E7A5A" },
    back: { area: { x: 0.14, y: 0.08, w: 0.72, h: 0.28 }, color: "#E9DCC3" },
  }),
  def({
    id: "roses",
    mood: "romance",
    layout: {
      size: [4800, 3191],
      credit: "Biel Morro / Unsplash",
      focus: { x: 0.6, y: 0.5 },
      zoom: 1,
      base: "#1E2B26",
      back: "photo",
      plate: { shape: "rect", fill: "#F3ECE1", opacity: 0.96, stroke: "#B79B7E", pad: 0.045, shadow: true },
    },
    textArea: { x: 0.2, y: 0.35, w: 0.6, h: 0.28 },
    justify: "center",
    title: { font: "cormorant", size: 0.074, color: "#3B1E22", weight: 500, lineHeight: 1.08 },
    soft: "#7A4A4E",
    names: { font: "cormorant", size: 0.04, italic: true, upper: false, tracking: 0, weight: 400 },
    ornament: { kind: "heart", color: "#A8343F" },
    back: { mirror: true },
  }),
  def({
    id: "velvet",
    mood: "romance",
    layout: {
      size: [4800, 3200],
      credit: "Kássia Melo / Unsplash",
      focus: { x: 0.5, y: 0.5 },
      zoom: 1,
      base: "#2A0D18",
      back: "photo",
      shade: { kind: "full", color: "#14040A", opacity: 0.3 },
      plate: { shape: "rect", fill: "#1C0610", opacity: 0.8, stroke: "#D9B77A", pad: 0.05 },
      frame: { color: "#D9B77A", inset: 8, double: true },
    },
    textArea: { x: 0.19, y: 0.34, w: 0.62, h: 0.3 },
    justify: "center",
    title: { font: "playfair", size: 0.084, color: "#F1D9A6", weight: 400, italic: true, lineHeight: 1.08 },
    soft: "#D8BC86",
    names: { color: "#C9A45C", tracking: 0.3 },
    ornament: { kind: "star", color: "#C9A45C" },
    back: { mirror: true },
  }),
  def({
    id: "lights",
    mood: "romance",
    layout: {
      size: [4465, 2977],
      credit: "Benjamin Wong / Unsplash",
      focus: { x: 0.55, y: 0.5 },
      zoom: 1,
      base: "#1A1208",
      back: "photo",
      plate: { shape: "rounded", fill: "#0F0A05", opacity: 0.66, stroke: "#E8C98A", pad: 0.05 },
    },
    textArea: { x: 0.17, y: 0.33, w: 0.66, h: 0.32 },
    justify: "center",
    title: serifItalic("#FFF1D2"),
    soft: "#F3D9A2",
    names: { color: "#E8C98A" },
    ornament: { kind: "star", color: "#E8C98A" },
    back: { mirror: true },
  }),
  def({
    id: "dusk",
    mood: "romance",
    layout: {
      size: [4800, 3194],
      credit: "krzhck / Unsplash",
      focus: { x: 0.62, y: 0.5 },
      zoom: 1,
      base: "#7A6E96",
      back: "photo",
      shade: { kind: "top", color: "#2B2350", opacity: 0.25, size: 0.5 },
    },
    textArea: { ...TOP, y: 0.1 },
    justify: "center",
    title: serifItalic("#FFFFFF", 0.108),
    soft: "#F4ECF6",
    ornament: { kind: "line", color: "#F4ECF6" },
    back: { ...backTop, color: "#FFFFFF" },
  }),
  def({
    id: "bouquet",
    mood: "romance",
    layout: { size: [4800, 3200], credit: "Earl Wilcox / Unsplash", focus: { x: 0.7, y: 0.275 }, zoom: 0.85, base: "#F3C3B0", back: "photo" },
    textArea: { ...TOP, y: 0.07 },
    justify: "center",
    title: serifItalic("#6E2238"),
    soft: "#8E4456",
    ornament: { kind: "heart", color: "#B8586F" },
    back: backMiddle,
  }),

  // ─── нежные ───
  def({
    id: "tenderness",
    mood: "tender",
    layout: {
      size: [4800, 3428],
      credit: "Cristina Anne Costello / Unsplash",
      focus: { x: 0.5, y: 0.5 },
      zoom: 1.05,
      base: "#CD7165",
      back: "photo",
      plate: { shape: "rounded", fill: "#FFF8F3", opacity: 0.94, stroke: "#D98A86", pad: 0.05, shadow: true },
    },
    textArea: { x: 0.2, y: 0.34, w: 0.6, h: 0.3 },
    justify: "center",
    title: serifItalic("#7A2733", 0.082),
    soft: "#9C4F55",
    names: { font: "cormorant", size: 0.04, italic: true, upper: false, tracking: 0, weight: 400 },
    ornament: { kind: "heart", color: "#D06A6E" },
    back: { mirror: true },
  }),
  def({
    id: "clouds",
    mood: "tender",
    layout: { size: [3201, 4800], credit: "Jei Lee / Unsplash", focus: { x: 0.5, y: 0.62 }, zoom: 1, base: "#E5859A", back: "photo" },
    textArea: { ...TOP, y: 0.1, h: 0.32 },
    justify: "center",
    title: serifItalic("#FFFFFF", 0.11),
    soft: "#FFF3F5",
    ornament: { kind: "line", color: "#FFFFFF" },
    back: { ...backTop, color: "#FFFFFF" },
  }),
  def({
    id: "dried",
    mood: "tender",
    layout: {
      size: [4800, 3840],
      credit: "Sixteen Miles Out / Unsplash",
      focus: { x: 0.55, y: 0.55 },
      zoom: 1,
      base: "#C6AC93",
      back: "photo",
      shade: { kind: "top", color: "#F3E4D6", opacity: 0.55, size: 0.45 },
    },
    textArea: { ...TOP, y: 0.06 },
    justify: "center",
    title: serifItalic("#4A2F21"),
    soft: "#6E4B38",
    ornament: { kind: "line", color: "#9A7458" },
    back: backTop,
  }),
  def({
    id: "eucalyptus",
    mood: "tender",
    layout: { size: [4608, 3456], credit: "Sincerely Media / Unsplash", focus: { x: 0.73, y: 0.357 }, zoom: 0.82, base: "#EAEAEA", back: "photo" },
    textArea: { ...TOP, y: 0.08, h: 0.3 },
    justify: "center",
    title: { font: "cormorant", size: 0.1, color: "#2F4537", weight: 500, lineHeight: 1.05 },
    soft: "#5A6E5F",
    ornament: { kind: "dots", color: "#7D9482" },
    back: backMiddle,
  }),
  def({
    id: "lavender",
    mood: "tender",
    layout: { size: [4800, 3200], credit: "Antony BEC / Unsplash", focus: { x: 0.5, y: 0.5 }, zoom: 1, base: "#746493", back: "photo" },
    textArea: { ...TOP, y: 0.07, h: 0.24 },
    justify: "center",
    title: serifItalic("#3B2357"),
    soft: "#5B4377",
    ornament: { kind: "line", color: "#5B4377" },
    back: { area: { x: 0.14, y: 0.08, w: 0.72, h: 0.26 } },
  }),
  def({
    id: "meadow",
    mood: "tender",
    layout: {
      size: [4272, 2848],
      credit: "Daniel Splisser / Unsplash",
      focus: { x: 0.55, y: 0.5 },
      zoom: 1,
      base: "#A28D7C",
      back: "photo",
      shade: { kind: "top", color: "#FFF7EC", opacity: 0.45, size: 0.4 },
    },
    textArea: { ...TOP, y: 0.07 },
    justify: "center",
    title: serifItalic("#3B2A20"),
    soft: "#5E4636",
    ornament: { kind: "line", color: "#8B6B52" },
    back: backTop,
  }),
  def({
    id: "mint",
    mood: "tender",
    layout: { size: [4592, 3448], credit: "A R / Unsplash", focus: { x: 0.7, y: 0.33 }, zoom: 0.85, base: "#889F8F", back: "photo" },
    textArea: { ...TOP, y: 0.07 },
    justify: "center",
    title: serifItalic("#2E4A3E"),
    soft: "#4E6A5D",
    ornament: { kind: "line", color: "#4E6A5D" },
    back: backMiddle,
  }),

  // ─── классика ───
  def({
    id: "flax",
    mood: "classic",
    layout: { size: [3200, 4800], credit: "Safwan Thottoli / Unsplash", focus: { x: 0.5, y: 0.5 }, zoom: 1.4, base: "#D6CBAE", back: "photo", frame: { color: "#8C7355", inset: 9, double: true } },
    textArea: { x: 0.16, y: 0.3, w: 0.68, h: 0.34 },
    justify: "center",
    title: { font: "cormorant", size: 0.088, color: "#4A3A2A", weight: 500, lineHeight: 1.08 },
    soft: "#6B5640",
    ornament: { kind: "line", color: "#8C7355" },
    back: { mirror: true },
  }),
  def({
    id: "saddle",
    mood: "classic",
    layout: {
      size: [3072, 4608],
      credit: "Felipe Santana / Unsplash",
      focus: { x: 0.5, y: 0.5 },
      zoom: 1.5,
      base: "#63300C",
      back: "photo",
      shade: { kind: "vignette", color: "#1E0E05", opacity: 0.45 },
      frame: { color: "#D4AF6A", inset: 8, double: true },
    },
    textArea: { x: 0.16, y: 0.28, w: 0.68, h: 0.36 },
    justify: "center",
    title: { font: "cormorant", size: 0.07, color: "#E7C885", weight: 600, upper: true, tracking: 0.08, lineHeight: 1.15 },
    soft: "#DDBB7A",
    names: { color: "#D4AF6A", tracking: 0.32 },
    ornament: { kind: "star", color: "#D4AF6A" },
    back: { mirror: true },
  }),
  def({
    id: "marble",
    mood: "classic",
    layout: { size: [4800, 3200], credit: "H&CO / Unsplash", focus: { x: 0.45, y: 0.5 }, zoom: 1, base: "#E3E3E3", back: "photo", frame: { color: "#B08D4E", inset: 10 } },
    textArea: { x: 0.14, y: 0.3, w: 0.72, h: 0.34 },
    justify: "center",
    title: { font: "playfair", size: 0.085, color: "#1D1D1F", weight: 400, lineHeight: 1.1 },
    soft: "#555555",
    names: { color: "#8C7140", tracking: 0.3 },
    ornament: { kind: "line", color: "#B08D4E" },
    back: { mirror: true },
  }),
  def({
    id: "alatau",
    mood: "classic",
    layout: { size: [4800, 3200], credit: "Etienne Bösiger / Unsplash", focus: { x: 0.42, y: 0.5 }, zoom: 1, base: "#879294", back: "photo" },
    textArea: { ...TOP, y: 0.1, h: 0.26 },
    justify: "center",
    title: { font: "cormorant", size: 0.105, color: "#1F3247", weight: 500, lineHeight: 1.05 },
    soft: "#3E5168",
    ornament: { kind: "line", color: "#3E5168" },
    back: backTop,
  }),
  def({
    id: "mist",
    mood: "classic",
    layout: { size: [4800, 3200], credit: "Julian Steenbergen / Unsplash", focus: { x: 0.32, y: 0.5 }, zoom: 1, base: "#53615C", back: "photo" },
    textArea: { ...TOP, y: 0.08 },
    justify: "center",
    title: serifItalic("#1E3328"),
    soft: "#3F5548",
    ornament: { kind: "line", color: "#3F5548" },
    back: backTop,
  }),
  def({
    id: "postcards",
    mood: "classic",
    layout: { size: [4800, 3204], credit: "rc.xyz NFT gallery / Unsplash", focus: { x: 0.48, y: 0.18 }, zoom: 0.78, base: "#0F100C", back: "photo" },
    textArea: { ...TOP, y: 0.07 },
    justify: "center",
    title: serifItalic("#F3E7D3"),
    soft: "#D9C9AE",
    names: { color: "#C9B08A" },
    ornament: { kind: "line", color: "#9C8664" },
    back: { area: { x: 0.14, y: 0.08, w: 0.72, h: 0.28 } },
  }),
  def({
    id: "milkyway",
    mood: "classic",
    layout: {
      size: [4096, 2733],
      credit: "Benjamin Voros / Unsplash",
      focus: { x: 0.5, y: 0.5 },
      zoom: 1,
      base: "#1B2436",
      back: "photo",
      shade: { kind: "bottom", color: "#000814", opacity: 0.55, size: 0.45 },
    },
    textArea: { ...BOTTOM, y: 0.66 },
    justify: "center",
    title: serifItalic("#FFFFFF"),
    soft: "#E6E9F5",
    names: { color: "#D9C9F0" },
    ornament: { kind: "star", color: "#E9D8FF" },
    back: { ...backBottom, color: "#FFFFFF" },
  }),
  def({
    id: "peaks",
    mood: "classic",
    layout: {
      size: [4800, 3200],
      credit: "Anurag Bhgsain / Unsplash",
      focus: { x: 0.55, y: 0.5 },
      zoom: 1,
      base: "#2A2E36",
      back: "photo",
      shade: { kind: "bottom", color: "#0A0F18", opacity: 0.45, size: 0.4 },
    },
    textArea: BOTTOM,
    justify: "center",
    title: { font: "cormorant", size: 0.1, color: "#FFFFFF", weight: 500, lineHeight: 1.05 },
    soft: "#E8EEF5",
    names: { color: "#F2C9B8" },
    ornament: { kind: "line", color: "#F2C9B8" },
    back: { ...backBottom, color: "#FFFFFF" },
  }),

  // ─── яркие ───
  def({
    id: "sakura",
    mood: "bright",
    layout: { size: [4800, 3200], credit: "Waldemar Brandt / Unsplash", focus: { x: 0.62, y: 0.5 }, zoom: 1, base: "#3E7DCC", back: "photo" },
    textArea: { ...BOTTOM, y: 0.64, h: 0.28 },
    justify: "center",
    title: serifItalic("#FFFFFF"),
    soft: "#EAF3FF",
    ornament: { kind: "line", color: "#FFFFFF" },
    back: { ...backBottom, color: "#FFFFFF" },
  }),
  def({
    id: "surf",
    mood: "bright",
    layout: { size: [4800, 3200], credit: "Kevin Kurek / Unsplash", focus: { x: 0.5, y: 0.5 }, zoom: 1, base: "#1F8C8F", back: "photo" },
    textArea: { ...TOP, y: 0.08, h: 0.3 },
    justify: "center",
    title: serifItalic("#FFFFFF", 0.105),
    soft: "#E6FAF8",
    ornament: { kind: "line", color: "#FFFFFF" },
    back: { ...backTop, color: "#FFFFFF" },
  }),
  def({
    id: "party",
    mood: "bright",
    layout: {
      size: [4800, 3204],
      credit: "Mockaroon / Unsplash",
      focus: { x: 0.5, y: 0.5 },
      zoom: 1,
      base: "#EEEEEE",
      back: "photo",
      plate: { shape: "rounded", fill: "#FFFFFF", opacity: 0.92, pad: 0.05 },
    },
    textArea: { x: 0.15, y: 0.34, w: 0.7, h: 0.3 },
    justify: "center",
    title: { font: "montserrat", size: 0.066, color: "#1F1B24", weight: 600, upper: true, tracking: 0.06, lineHeight: 1.15 },
    soft: "#5B5563",
    subtitle: { font: "montserrat", size: 0.032, italic: false, weight: 400 },
    names: { color: "#E2475B", tracking: 0.2 },
    ornament: { kind: "dots", color: "#E2475B" },
    font: "montserrat",
    back: { mirror: true },
  }),
  def({
    id: "autumn",
    mood: "bright",
    layout: { size: [3200, 4800], credit: "Cole Keister / Unsplash", focus: { x: 0.5, y: 0.38 }, zoom: 1, base: "#C8D3D6", back: "photo" },
    textArea: { ...TOP, y: 0.06, h: 0.24 },
    justify: "center",
    title: serifItalic("#7A1E14"),
    soft: "#9A3F2E",
    ornament: { kind: "line", color: "#B5543E" },
    back: { area: { x: 0.14, y: 0.08, w: 0.72, h: 0.26 } },
  }),
  def({
    id: "steppe",
    mood: "bright",
    layout: {
      size: [4800, 3200],
      credit: "Johnny McClung / Unsplash",
      focus: { x: 0.45, y: 0.5 },
      zoom: 1,
      base: "#7A5A22",
      back: "photo",
      shade: { kind: "bottom", color: "#2A1806", opacity: 0.55, size: 0.5 },
    },
    textArea: { ...BOTTOM, y: 0.66 },
    justify: "center",
    title: serifItalic("#FFF4DE"),
    soft: "#F6E3BE",
    names: { color: "#F0D49C" },
    ornament: { kind: "line", color: "#F0D49C" },
    back: backBottom,
  }),
];
